#!/bin/bash

if (( UID != 0 )); then
    echo "$0: needs to run as root!" 1>&2
    exit 1
fi

for device in /sys/class/drm/card?/device; do
    if [[ -e "$device"/pp_power_profile_mode ]]; then

        echo manual > "$device"/power_dpm_force_performance_level
        echo 1 > "$device"/pp_power_profile_mode

        # The other power profile modes are:
        #   0 = BOOTUP_DEFAULT
        #   1 = 3D_FULL_SCREEN
        #   2 = POWER_SAVING
        #   3 = VIDEO
        #   4 = VR
        #   5 = COMPUTE
    fi
done
